version: "3.8"

services:
  predictor-app:
    build:
      context: .
    ports:
      - "8000:8000" 
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
